<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17178" started-at="2016-07-20T21:53:57Z" finished-at="2016-07-20T21:54:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17178" started-at="2016-07-20T21:53:57Z" finished-at="2016-07-20T21:54:14Z">
      <class name="testcases.TestCase1">
        <test-method status="PASS" signature="createInstance()[pri:0, instance:testcases.TestCase1@6276ae34]" name="createInstance" is-config="true" duration-ms="12007" started-at="2016-07-20T14:53:57Z" finished-at="2016-07-20T14:54:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createInstance -->
        <test-method status="FAIL" signature="testCalc()[pri:0, instance:testcases.TestCase1@6276ae34]" name="testCalc" duration-ms="5082" started-at="2016-07-20T14:54:09Z" finished-at="2016-07-20T14:54:14Z">
          <exception class="com.thoughtworks.selenium.SeleniumException">
            <message>
              <![CDATA[ERROR: Element xpath=.//*[@id='cloanamount'] not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: Element xpath=.//*[@id='cloanamount'] not found
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:111)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:105)
	at com.thoughtworks.selenium.DefaultSelenium.type(DefaultSelenium.java:322)
	at testcases.TestCase1.testCalc(TestCase1.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- com.thoughtworks.selenium.SeleniumException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCalc -->
        <test-method status="PASS" signature="stop()[pri:0, instance:testcases.TestCase1@6276ae34]" name="stop" is-config="true" duration-ms="66" started-at="2016-07-20T14:54:14Z" finished-at="2016-07-20T14:54:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stop -->
      </class> <!-- testcases.TestCase1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
